### ISSUE TITLE
Question: Why is the property named "dist"?

### ISSUE THREAD

**Issue by jt000** [assemble/generator-assemble#59]
Purely out of curiosity, why is the variable named `config.dist` in [Gruntfile.js line 28](https://github.com/assemble/generator-assemble/blob/master/app/templates/Gruntfile.js#L28)? I would've assumed it'd be named `config.dest` as in "destination". Typo or is there a significance to `dist`?

**Comment by pburtchaell** [comment]
It is probably better to hold this conversation at [assemble/assemble](http://github.com/assemble/assemble).

**Comment by jonschlinkert** [comment]
I'll just answer here. @jt000 `dist` is for `distribution`. Since it's just used as an arbitrary property here I can see how that might look like a typo. I've been using `_gh_pages` a lot in examples lately. 

fwiw, we'll be releasing a new version of this soon, since assemble v0.6.0 is finally in beta

**Comment by jonschlinkert** [comment]
thanks @pburtchaell

**Comment by jt000** [comment]
Ah, thanks @jonschlinkert for the clarification. I hadn't seen that before...

**Comment by jonschlinkert** [comment]
no prob, thanks for asking :)
